### PR TITLE
update to open62541 v1.3.9

### PR DESCRIPTION
**Pull request by moniwe**

### CODE REVIEW

**Comment by azoitl** [comment]
@jwalt can you please have a look.

**Comment by moniwe** [comment]
@jwalt i would have added you as reviewer, if the system would have shown your name within the list. Not sure if i am the only one not able to see you within this selection list.

**Comment by azoitl** [comment]
> @jwalt i would have added you as reviewer, if the system would have shown your name within the list. Not sure if i am the only one not able to see you within this selection list.

@moniwe I forgot to add that this is a Github issue. In the list of potential reviewers only members of the project/organization are listed.

**Comment by jwalt** [comment]
I haven't tested it, but that is how a trivial version update is supposed to work. Try `scripts/run-build-test.sh` to check. That does contain a few hiccups if you do not have a full toolchain install yet, which is fixed in a different PR

**Review by azoitl — APPROVED** [review]

**Pull request merged**
